### ISSUE TITLE
Voucher validato in Debug client assertion - 400 bad request

### ISSUE THREAD

**Issue by 0biWanKenobi** [pagopa/pdnd-interop-frontend#1290]
**Il codice IPA del tuo ente**
icaic

**Data e ora del tentativo**
10/06/2025 h. 09:20

**Ambiente**
Collaudo

**client_id**
`f9e3ed3d-96b2-425e-8918-13f9ed510225`

**correlationId**
`87ed88ce-3e37-4077-b0c5-5a30f472fc75`

**purposeId (solo per i client e-service)**
`3562da10-4e03-4f53-86ec-b1515d03f5c4`

Url chiamato: `https://auth.uat.interop.pagopa.it/token.oauth2`

JWT generato:

```
eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6Ik1lZF9mTGZBZTZJcm5wRENHQ0FzSURhOXBGZFl5WnhrVXRQYjZic1ZrdFUifQ.eyJqdGkiOiJkZTAwYWRmMS04ZWFiLTRiNzQtOGM1YS04NGIyYjBjNTJlZmQiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwic3ViIjoiZjllM2VkM2QtOTZiMi00MjVlLTg5MTgtMTNmOWVkNTEwMjI1IiwiaXNzIjoiZjllM2VkM2QtOTZiMi00MjVlLTg5MTgtMTNmOWVkNTEwMjI1IiwiZXhwIjoxNzQ5NTQzNzAzLCJpYXQiOjE3NDk1NDAxMDMsImNsaWVudF9pZCI6ImY5ZTNlZDNkLTk2YjItNDI1ZS04OTE4LTEzZjllZDUxMDIyNSIsInB1cnBvc2VJZCI6IjM1NjJkYTEwLTRlMDMtNGY1My04NmVjLWIxNTE1ZDAzZjVjNCIsImVzZXJ2aWNlSWQiOiI1MTc5OTQzOS04NTc1LTQ4ZDQtOGU5NS05MDY5MjZhYjhlNDciLCJkZXNjcmlwdG9ySWQiOiI0MDk3NjlmNi1jN2UyLTQwYzMtYmY5NC00NzQyNGU1Y2NiN2MiLCJwcm9kdWNlcklkIjoiODQ4NzFmZDQtMmZkNy00NmFiLTlkMjItZjZiNDUyZjRiM2M1IiwiY29uc3VtZXJJZCI6IjAyYzYzMDcxLWFlMmQtNDVlNS1iOWIyLTI1OWUyNzAyNzRkMCJ9.WSnlHrZBQ3BCULs06TNwYgerZo5JXDydrtEsTCxObMcY_XAd-6Y7yUXX-8OS1udz3SP4AFuwwqKznR92YCar_zce6oJTGhMRzFUL-fAv6qDc2QWIuhGIjzHRv_ajl5QiEdu-nVHM4-Z4g7HoYPF9Sm186Me-oKS-YsfoFljkZ5G1xZMmTdUhn_9-Cl48fShg1uDVrNxQxdz6N8-13i9eFMrHAa7j7-qZTnO8eU4EBxkDOTjiMv4yYRLWmuBs-omDfmK-U_aKtRlwWB-ixiHFapgLFaz30A_t1icPy-IMX32faHRyVmZIWGdd4q81t7ctCWGYl9dG8JV1LZyXvgED5g
```

Nonostante la risposta positiva da Debug Client Assertion, riceviamo sempre 400 Bad Request.

![Image](https://github.com/user-attachments/assets/756de610-0a55-4d11-8ba7-2da6f14acf49)

**Comment by 0biWanKenobi** [comment]
Aggiungo il body della chiamata, in formato `application/x-www-form-urlencoded`

```yaml
grant_type: client_credentials
client_id: f9e3ed3d-96b2-425e-8918-13f9ed510225
client_assertion: eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCIsI...
client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
```
